### ISSUE TITLE
Open STT License Violation

### ISSUE THREAD

**Issue by snakers4** [1ytic/open_stt_e2e#1]
Looks like this repo violates the Open STT [license](https://github.com/snakers4/open_stt#license) in several ways. 

As a quick reminder, Open STT is published under CC-NC-BY https://creativecommons.org/licenses/by-nc/4.0/.

I have opened this issue to document this license violation, which was not remedied immediately after we contacted the repo author.

(0)
Judging by this repo author's profile (@1ytic), he works for SpeechPro / ЦРТ.
We, as dataset authors, have not been contacted by this company and we have not agreed on the terms of commercial usage by said company and we do not by any means endorse this usage.

(1)
This repo contains a link to a re-upload of Open STT.
This re-upload itself does not contain any links to the original dataset and the original license.
As a quick refresher, BY in the CC-NC-BY stands for:

> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

(2)
This repo itself is licensed under MIT, which also is against the "NC" and "BY" part of the official license. This repo users can therefore be misled to assume that the Open STT dataset is under MIT license or similar.

Please make the according changes immediately.

**Comment by 1ytic** [comment]
First of all, my employer has nothing to do with this repo. Secondly, I uploaded the LICENSE file yesterday. Thirdly, I do not think that MIT license of this repo violates the Open STT license.

**Comment by snakers4** [comment]
> secondly, I uploaded the LICENSE file yesterday.

Many thanks. But there is still no clear visible / discernible link to Open STT there.
Please amend your hosting so that it is obvious that the dataset is a re-upload or please delete it

![image](https://user-images.githubusercontent.com/12515440/79683813-3b6b8080-8235-11ea-9fc0-22e1ac942438.png)

>  I do not think that MIT license of this repo violates the Open STT license.

An NC license merely means that no commercial use is allowed unless agreed with authors.
The MIT license allows commercial use.
We have not agreed that users of your repo can use Open STT comerrcially.
So you are misleading the end-users that can visit this repo, and download via direct links. Please amend that.

**Comment by 1ytic** [comment]
Added the README file to the bucket. Is it okay for you?

**Comment by snakers4** [comment]
> Added the README file to the bucket. Is it okay for you?

Yes. People usually read README files.

**Comment by 1ytic** [comment]
Could you close the issue or is something else bothers you?

**Comment by snakers4** [comment]
This part

> An NC license merely means that no commercial use is allowed unless agreed with authors.
The MIT license allows commercial use.
We have not agreed that users of your repo can use Open STT commercially.
So you are misleading the end-users that can visit this repo, and download via direct links. Please amend that.

I believe the equivalent in terms of software licenses is the GPL family licenses. Otherwise it seems that the goal of this project is to create a legal "proxy" to use Open STT commercially w/o agreement with authors.

**Comment by 1ytic** [comment]
With all due respect, you overestimate the importance of your data. The goal of this project is to show a simple approach for STT task. As soon as possible I will use the [Common Voice](https://voice.mozilla.org/en/datasets) from Mozilla. Now, as a workaround, I can add a NC license for pre-trained models. Will this solve the issue?

**Comment by snakers4** [comment]
If the data is not important - please do not use it and moreover - re-upload it.

As long long the license is clearly non-commercial or GPL - it is fine with me.

Prohibiting particular users to use the dataset would go against the spirit of our work, but so does yours.

**Comment by 1ytic** [comment]
Oh boy, instead of wasting time on litigation, you'd better to clean up your dataset and hope that at least someone will use it. I uploaded the LICENSE file for the pre-trained models.
