### ISSUE TITLE
CTC model source paper ?

### ISSUE THREAD

**Issue by songtaoshi** [1ytic/open_stt_e2e#2]
Hi, Thanks for nice work sharing of RNN-T.     

I am wondering if any paper the ctc model is referenced to?   

Is the mask conv like the mask conv in pixel CNN?

**Comment by 1ytic** [comment]
I recommend to read [Deep Speech 2](https://arxiv.org/abs/1512.02595) paper from Baidu. The mask conv is similar to this [implementation](https://arxiv.org/abs/1512.02595), but slightly optimised for speed.

**Comment by songtaoshi** [comment]
Thanks a lot !
