### ISSUE TITLE
question about frames filtering restriction

### ISSUE THREAD

**Issue by songtaoshi** [1ytic/open_stt_e2e#3]
Hi, 1ytic, I am a little confused about the **frame restriction**:   
why we need to restrict the text frames  <= acoustic frames?

**Comment by 1ytic** [comment]
This limitation is due to the CTC loss, which implies monotone alignment of target labels with a maximum of one label in one frame. Also, you should not forget a blank symbol in the target labels.

**Comment by songtaoshi** [comment]
thanks for your reply and tip! RNN-T should not have such restriction. Thanks!
