### ISSUE TITLE
Question about Prior

### ISSUE THREAD

**Issue by khursani8** [1ytic/open_stt_e2e#4]
Hi, thanks for the code I learned a lot by reading your code especially the reinforcement learning one.

In the code I saw that you use prior during prediction, is there any reason why or any resource I can look at to?

Thanks :)

**Comment by 1ytic** [comment]
You are welcome. The prior is usually used for overfitted models in practice. In this case, I used relatively small dataset and did not use augmentation techniques. Therefore, using the prior information helped for this case.

**Comment by khursani8** [comment]
Got it, thanks!!
