### ISSUE TITLE
Question About LM forward | step_features  & step_forward

### ISSUE THREAD

**Issue by songtaoshi** [1ytic/open_stt_e2e#5]
Hi, @1ytic, Thanks for reading my issue.  I am confused why there exists forward & step_features & step_forward in 
```python
    def forward(self, x, lengths, head=True):
        init = torch.zeros((1, x.shape[1]), device=x.device, dtype=torch.long)
        x = torch.cat([init, x.long()])
        x = self.emb(x)
        x = pack_padded_sequence(x, lengths + 1, enforce_sorted=False)
        x, _ = self.rnn(x)
        data = self.prj(x.data)
        if head:
            data = self.fc(data)
            data = log_softmax(data, dim=-1)
        x = PackedSequence(data, x.batch_sizes, x.sorted_indices, x.unsorted_indices)
        x, _ = pad_packed_sequence(x)
        return x

    def step_features(self, x, h=None):
        x = self.emb(x)
        x, h = self.rnn(x, h)
        x = self.prj(x)
        return x, h

    def step_forward(self, x, h=None):
        x, h = self.step_features(x, h)
        x = x.view(-1, x.size(-1))
        x = self.fc(x)  # T x N x H
        return x, h
```

I see step_forward & step_features in train_lm but forward in train_rnnt. 

I can not figure out why there should do such implementation.

**Comment by 1ytic** [comment]
Hi, @songtaoshi. `step_forward` function doesn't care about the sequences in batch, on the other hand, `forward` takes care of the sequences with different lengths. For example, when I train LM, I use `step_forward`, because the specially prepared batch consists of equal size sequences. But when I train RNN-T model, I use `forward` instead.

**Comment by songtaoshi** [comment]
Got it, I am not familiar with LM training and suppose there exists sequence of different lengths. Really thanks for your reply @1ytic !
